development:
  archive: /Users/mrnugget/code/projects/archive/spec/fixtures/archive
  download_url: file://localhost/Users/mrnugget/rails/archive/spec/fixtures/archive/

test:
  archive: /Users/mrnugget/code/projects/archive/spec/fixtures/archive
  download_url: file://Users/mrnugget/rails/archive/spec/fixtures/archive/

production:
  archive: /var/www/aufnahmen
  download_url: http://91.121.150.109/aufnahmen/
